#+DATE:  2025-02-27T02:55:45+06:00
#+DRAFT: false
#+TITLE: National Conference on Physics: 2025

This is the first conference I have attended as a Presenter.
I preseted my research poster on ion-ion interaction in Liquid metals.
I was also a volunteer for this event, working for Bangladesh Physical Society.

I utilized the event to visit Rajshahi City knowing fully well that this may be the only time I will get such an opportunity.
I saw the [[https://en.wikipedia.org/wiki/Rajshahi_College][Rajshahi College]], the [[https://en.wikipedia.org/wiki/University_of_Rajshahi][University of Rajshahi]], the New market. I also visited the silk mills.
Unfortunately the [[https://en.wikipedia.org/wiki/Varendra_Research_Museum][Varendra Museum]] was closed during this time (Thursday, Friday).
Because of time constraints I could not visit the [[https://en.wikipedia.org/wiki/Puthia_Rajbari][Puthia Rajbari]]. I left for Dhaka on Friday night.

The whole team from the University of Dhaka (along with some esteemed Professors and their students from BUET, SUST and JnU) went there on Wednesday (5th February), by train. But I was not aware that the museum would be closed during Thursdays.
This was my first ever train journey. I enjoyed it. It reminds me of the launch service I enjoy from Dhaka to Barishal and vice versa (alas this service slowly dying). I hope train service will oneday be available for people of Barishal.
